name: Build Flutter APK
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop # Die Umgebung, die verwendet werden soll.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
      - name: Change directory to project root
        run: cd dlrg_weeze_manager && flutter pub get  # <-- Korrigiert: run verwendet
      #- name: Install dependencies
       # run: flutter pub get
      - name: Check Flutter Doctor
        run: flutter doctor -v
      - name: Build APK
        run: flutter build apk --debug
        working-directory: dlrg_weeze_manager
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DLRG Community Manager.apk
          path: dlrg_weeze_manager/build/app/outputs/flutter-apk/app-debug.apk

